export const popSearchArr = [
    { id: 1, name: "Avocado Toast" },
    { id: 2, name: "Bubble Tea" },
    { id: 3, name: "Plant-Based Burger" },
    { id: 4, name: "Keto Brownies" },
    { id: 5, name: "Matcha Latte" },
    { id: 6, name: "Sushi Burrito" },
    { id: 7, name: "Vegan Cheese" },
    { id: 8, name: "Charcoal Ice Cream" },
    { id: 9, name: "Spicy Ramen" },
    { id: 10, name: "Acai Bowl" },
    { id: 11, name: "Cloud Bread" },
    { id: 12, name: "Taco Pizza" },
    { id: 13, name: "Kombucha" },
    { id: 14, name: "Rainbow Bagel" },
    { id: 15, name: "Street Tacos" },
    { id: 16, name: "Pulled Jackfruit" },
    { id: 17, name: "Korean Fried Chicken" },
    { id: 18, name: "Fried Avocado" },
    { id: 19, name: "Sourdough Bread" },
    { id: 20, name: "Cronut" },
    { id: 21, name: "Poke Bowl" },
    { id: 22, name: "Impossible Burger" },
    { id: 23, name: "Oat Milk Latte" },
    { id: 24, name: "Turmeric Latte" },
    { id: 25, name: "Vegan Pancakes" },
    { id: 26, name: "Spicy Pickles" },
    { id: 27, name: "Birria Tacos" },
    { id: 28, name: "Pho" },
    { id: 29, name: "Shakshuka" },
    { id: 30, name: "Tamago Sando" },
    { id: 31, name: "Cheeseburger Eggrolls" },
    { id: 32, name: "Ramen Burger" },
    { id: 33, name: "Thai Rolled Ice Cream" },
    { id: 34, name: "Zucchini Noodles" },
    { id: 35, name: "Eggplant Parmesan" },
    { id: 36, name: "Churro Sundae" },
    { id: 37, name: "Elote (Mexican Street Corn)" },
    { id: 38, name: "Lavender Lemonade" },
    { id: 39, name: "Hot Honey Chicken" },
    { id: 40, name: "Chimichurri Steak" },
    { id: 41, name: "Boba Pancakes" },
    { id: 42, name: "Sweet Potato Toast" },
    { id: 43, name: "Tofu Scramble" },
    { id: 44, name: "Rice Paper Dumplings" },
    { id: 45, name: "Focaccia Art" },
    { id: 46, name: "Mango Sticky Rice" },
    { id: 47, name: "Kale Caesar Salad" },
    { id: 48, name: "Ube Cheesecake" },
    { id: 49, name: "Carrot Bacon" },
    { id: 50, name: "Fried Oreos" },
    { id: 51, name: "Chili Oil Dumplings" },
    { id: 52, name: "Falafel Wrap" },
    { id: 53, name: "Vietnamese Iced Coffee" },
    { id: 54, name: "Honey Butter Chips" },
    { id: 55, name: "Cauliflower Tacos" },
    { id: 56, name: "Smash Burger" },
    { id: 57, name: "Seaweed Chips" },
    { id: 58, name: "S’mores Brownies" },
    { id: 59, name: "Gourmet Popcorn" },
    { id: 60, name: "Breakfast Burrito" },
    { id: 61, name: "Halloumi Fries" },
    { id: 62, name: "Miso Soup" },
    { id: 63, name: "Coconut Yogurt" },
    { id: 64, name: "Bacon-Wrapped Dates" },
    { id: 65, name: "Stuffed Bell Peppers" },
    { id: 66, name: "Chia Pudding" },
    { id: 67, name: "Gyoza" },
    { id: 68, name: "Banh Mi" },
    { id: 69, name: "Ravioli Lasagna" },
    { id: 70, name: "Avocado Smoothie" },
    { id: 71, name: "Kimchi Pancakes" },
    { id: 72, name: "Ice Cream Sandwich" },
    { id: 73, name: "Cuban Sandwich" },
    { id: 74, name: "Peanut Butter Protein Balls" },
    { id: 75, name: "Molten Lava Cake" },
    { id: 76, name: "Japanese Souffle Pancakes" },
    { id: 77, name: "Matcha Cookies" },
    { id: 78, name: "Sticky Toffee Pudding" },
    { id: 79, name: "Dalgona Coffee" },
    { id: 80, name: "Rose Water Baklava" },
    { id: 81, name: "Churros" },
    { id: 82, name: "Gourmet Mac and Cheese" },
    { id: 83, name: "Pumpkin Spice Latte" },
    { id: 84, name: "BBQ Pulled Pork" },
    { id: 85, name: "Nashville Hot Chicken" },
    { id: 86, name: "Pasta Carbonara" },
    { id: 87, name: "Beef Wellington" },
    { id: 88, name: "Chocolate Fondue" },
    { id: 89, name: "Chicken Alfredo" },
    { id: 90, name: "Mini Cheesecakes" },
    { id: 91, name: "Pasta Primavera" },
    { id: 92, name: "Lobster Roll" },
    { id: 93, name: "Fish Tacos" },
    { id: 94, name: "Buffalo Cauliflower" },
    { id: 95, name: "Grilled Shrimp Skewers" },
    { id: 96, name: "Spinach and Artichoke Dip" },
    { id: 97, name: "Beet Salad" },
    { id: 98, name: "Chorizo Queso Dip" },
    { id: 99, name: "Stuffed Mushrooms" },
    { id: 100, name: "Pineapple Fried Rice" },
    { id: 101, name: "Banana Pancakes" },
    { id: 102, name: "Egg Drop Soup" },
];